### ISSUE TITLE
Notifications are not sent when a proxy is removed.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#1025]
### Descriptive summary

When a proxy is added, both the owner and the proxy receive notifications on the Dashboard.  When a proxy is deleted, no new notification is generated for the owner or the proxy.

### Expected behavior
A proxy deletion would generate a notification for both owner and proxy.

### Actual behavior
No notifications.

Not sure that this counts as a bug or feature incompleteness.

**Comment by newmanld** [comment]
See also #1024

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/450
