### ISSUE TITLE
I can assign myself to be my own proxy.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#1027]
### Descriptive summary

I can assign myself as my own proxy.

### Expected behavior
I should not be able to find myself when searching for users to assign as a proxy, or be able to assign myself as my own proxy.  

### Actual behavior
I can assign myself as my own proxy.  When submitting a new work, I am then given a choice to submit on behalf of myself, or on behalf of my email address.

**Comment by crowesn** [comment]
https://github.com/projecthydra/sufia/issues/2454

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/675
