### ISSUE TITLE
Develop method to collect repository usage statistics

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc_legacy#11]

**Comment by flutterflies** [comment]
What is the status of this? Is our current Google Analytics setup meeting out needs?

**Comment by newmanld** [comment]
I think the answer is No.  We need to be sure that the Analytics built into the GUI which depend on Google Analytics today, are in fact working, but we also need a more robust reporting system using system logs, with  decisions made on how to de-personalize and how long to retain those system logs.  Changing milestone to Scholar 3.x.
