### ISSUE TITLE
Export as a Refworks Citation

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1177]
### Descriptive summary

I want to: have an option to cite using RefWorks.  So that: I am able to export a particular work's citation into RefWorks citation management system.    

 #Acceptance criteria 

RefWorks options appears alongside EndNote, Zotero, Mendeley on show page for a work.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/799
