### ISSUE TITLE
Student Work:  Submission should notify advisor.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1178]
### Descriptive summary

As a: Student Submitter. I want to: notify my advisors when I submit a work and select them as the advisor. So that: my advisor knows my student work has been posted in the repository. 

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/798
