### ISSUE TITLE
Add a fair use button so that embargoed articles can be included in Scholar.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1180]
### Descriptive summary

as a part of the Institutional Repository's interface. If a
would-be user reaches a Closed Access deposit, they can cut/paste
their email address into a box, and click on the "Fair Use"
Button, which sends an automatic email request to the author,
asking for authorization to email one individual eprint to the
requester, for personal research use. The author can then just
click on a URL to authorize the emailing of that individual
eprint.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/797
