### ISSUE TITLE
Finalize Charles Woodman large file Ingest

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1238]
### Descriptive summary

See Spreadsheet.

**Comment by scherztc** [comment]
Notified Charles of FREEZE on large file ingestion.  We ingested 32/56 of the videos.  We will pick this up again when the Scholar 3 upgrade is complete.

**Comment by scherztc** [comment]
Research : Method for ingestion of files bigger than 3GB.
Link to Documentation in Wiki.
Provide status update on issue.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/686
