### ISSUE TITLE
Configure Hydra-remote_identifiers to support resource_types

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc_legacy#130]
I've added appropriate types to our models in Curate_fork, but the code we're using to register DOIs doesn't currently support inclusion of the type field. We'll have to fork the projecthydra-labs/hyrda-remote_identifers and add this functionality. (I've had a short look at that gem, and it doesn't look like too difficult a task.)

**Comment by hortongn** [comment]
@jamesvanmil In your opinion, is this something we should still do with our current version of Scholar (add resource types to DOIs)?

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/599#issuecomment-475394105
