### ISSUE TITLE
View Collection with facets and limits

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1509]
### Descriptive summary

As a collection browser: I want to be able view a collection in a catalog experience with facets and limits. Is this important?

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
This feature now exists in Scholar 4.0 (from Hyrax 2.x)
