### ISSUE TITLE
Bulk Download Option

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1510]
### Descriptive summary

As a: User. I want: a bulk download option from the collection page. So that: I can quickly retrieve all items included in the particular collection. Acceptance criteria: ?

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related issues or prior related work here.

**Comment by hortongn** [comment]
Resolved by https://github.com/uclibs/ucrate/pull/627 and https://github.com/uclibs/ucrate/pull/664
