### ISSUE TITLE
File Manager is difficult to find

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1799]
### Descriptive summary

File manager

I wanted to adjust the thumbnail of the work. I was not able to locate the file manager very easily. I tried to search for it in several locations, until eventually finding. I wondered if it can be added to the pull down menu for the file, or as a button near the edit button. 

### Expected behavior

That File Manager would be more accessible from the drop-down and not be buried in the EDIT view.

**Comment by hortongn** [comment]
The File Manager button is now more visible in Scholar 4.0.  Probably not work the technical debt we would incur by overriding the location.
