### ISSUE TITLE
Customize User Profile Pages for the fields that we want

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#18]
Collect feedback from DR Task Force to inform our own customization of the User Profile pages.  Fields such as gender and age may not be desirable.  Other fields may be needed.  One such field that may be needed is a link to the full faculty profile page in UC's Research Directory / Eprofessional system.  For example:
http://research.uc.edu/expertprofile.aspx?epersonID=twomeyj&search=Twomey
or alternatively, the user could decide to link to a similar page on their department's website or elsewhere:
http://www.artsci.uc.edu/departments/english/profiles/jay_twomey.html

**Comment by flutterflies** [comment]
Closing this. User profiles no longer exist in Scholar 3 and the information presented on the user page only pertains to the user's role/job at the university

**Comment by newmanld** [comment]
Re-opening this as we have some work in our near future to customize user profile pages, with an integration with UC's Research Directory which do exist in Scholar 3 (See People Tab and see my profile at https://scholar.uc.edu/users/newmanld@ucmail-dot-uc-dot-edu).    Changing the milestone to 3.x.  Note that the 'collect feedback' in the opening description should now include our Product Owners.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/731
