### ISSUE TITLE
Upgrade Hyrax to version 2.1

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1802]
### Descriptive summary

Upgrade the core gem hyrax to version 2.

### Expected behavior

Test should pass.
All features should migrate.

https://github.com/samvera/hyrax/tree/2.0-stable

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/wiki/Hyrax-Management-Guide\

**Comment by scherztc** [comment]
https://github.com/samvera/hyrax/releases/tag/v2.0.0

**Comment by jayanthdeejay** [comment]
Solr reindex is required after upgrading to Hyrax 2.0.0/1

**Comment by scherztc** [comment]
Develop on 2.1.0beta

Identify the namespace changes
Identify the overrides
Identify the features that have been deleted
Identify the features that have been added
Initial configuration settings
Database Migrations
Content Migration concerns
GUI changes
Code clean up
Sys Admin stuff
Test passing

**Comment by hortongn** [comment]
Already implemented
