### ISSUE TITLE
Author field should be ordered

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1803]
### Descriptive summary

Some metadata fields like author should be ordered.  The order should be available to the creator.  

### Expected behavior

Test should pass.
Creators should be able to modify the order of the author field on creation and edit.
This order should be preserved in Fedora.

 https://groups.google.com/forum/#!topic/samvera-tech/g1oa5B2B0Wk

**Comment by scherztc** [comment]
https://github.com/psu-stewardship/scholarsphere/blob/develop/app/models/concerns/has_creators.rb#L14

**Comment by scherztc** [comment]
At Durham we have done this in a few different ways, depending on where exactly we need it. 

In our Sufia 6 based repository, where we have literal values that need to be ordered, we wrap them in nested resources that then contain the literal value along with an order property. Then there's some wrapper code that (un)wraps these and sorts them according to the order so in your model you can just set and get an array and all the rest happens automatically [1] (most of the relevant code is in the ordered_property class method, the rest is just dealing with loading from Solr). In your model you just define your properties with property_with_order instead of property and then use it like any other property. 

Then we have some objects with belongs_to that need to be kept ordered in the object they belong to. These also store an order property in them and there's some wrapper code in the containing object that returns them in the right order [2] and [3].

Finally some ordered relationships we've implemented simply by serialising the related object ids in a string literal in the containing object. Then there's methods to unpack them and find them all from Fedora/Solr. This we use in places where we expect hundreds of related objects and where the standard PCDM solution has performance issues. The fact that this also preserves ordering is an added bonus. (I don't have code for this in public github unfortunately).

The need for ordered properties certainly comes up quite regularly and having a standard solution for it would be fantastic.

Olli

[1] https://github.com/durham-university/collections/blob/master/app/models/concerns/hydra_durham/ordered_property.rb#L52

[2] https://github.com/durham-university/collections/blob/master/app/models/concerns/hydra_durham/metadata.rb#L20-L26
[3] https://github.com/durham-university/collections/blob/master/app/models/contributor.rb

**Comment by jamesvanmil** [comment]
This group is planning to complete this work by June 30, 2018:

https://wiki.duraspace.org/display/samvera/Hyrax+Metadata+Ordering+Working+Group

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/612
