### ISSUE TITLE
Confirm that DOI handshakes take place correctly.

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#1834]
### Descriptive summary

Confirm that our app in Hyrax 2.x has the correct handshakes in place with the EZID system for basic functionality including:
* minting a DOI
* reserving a DOI on a private or embargoed work
* changing status of DOI from reserved to public when a private or embargoed work become public.
* updating information in the EZID system if core metadata reported to that system changes.
* generating tombstone in EZID system if a work with a DOI is deleted.

Create any documentation needed to help with planned shift from EZID API to Datacite API.

See recent work merged for our app in Hyrax 1.x on #1816.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/599#issuecomment-475238466
