### ISSUE TITLE
Proxy problem : On behalf of on the EDIT screen is causing permission problems with works.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#1840]
### Descriptive summary

If a proxy changes the On behalf of on the EDIT screen, then the proxy and user are unable to edit work or use the file manager.  

Should this even be visible on this screen?  
What is is doing to permissions?
What is it doing to owner transfer?
Does the user have to change the On behalf of or just its existance is causing problems when saving a work?

### Expected behavior

It is expected that the On Behalf of only be available on work creation and not on edit.

### Actual behavior

You see it on both.

Bugs - 
    If she submits as Dave's proxy, she is losing the file manager.  
    If she submits on behalf of herself, transfer of ownership to Dave isn't working.
     
    Most works are private - it's possible that's a factor.

    May relate to the bug discovered by Olivia - proxy deposit may (?) still be functioning correctly on original deposit, but once a work is edited by a proxy, rights may get screwed up.

**Comment by scherztc** [comment]
Examing this on DEV, I found that when editing a work submitted on behalf of faculty the only option viewable in the drop down is the proxy.

<img width="429" alt="screen shot 2018-04-10 at 12 38 59 pm" src="https://user-images.githubusercontent.com/5084562/38570766-96449962-3cbc-11e8-9520-510c3903ab0f.png">

Clicking on it has no affect on EDIT permissions for the faculty or the proxy

**Comment by scherztc** [comment]
I have run through multiple scenarios with PROXY and FACULTY and all of the permissions seem to hold true:

PROXY EDIT WORK / DON’T CHANGE ON BEHALF OF / APPLY CHANGES 
PROXY EDIT WORK / CHANGE ON BEHALF OF TO FACULTY/ APPLY CHANGES 
AFTER TRANSFER OF OWNERSHIP TO FACULTY
REMOVAL OF PROXY

**Comment by scherztc** [comment]
@newmanld When you edit a work you submitted on behalf of someone, what do you see in the drop down?

**Comment by hortongn** [comment]
Fixed in Scholar 4.0
