### ISSUE TITLE
Adjust information in Scholar@UC to be compliant with FERPA

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#1896]
### Descriptive summary

FERPA is a federal law about the privacy of student records.  https://www2.ed.gov/policy/gen/guid/fpco/ferpa/index.html
The UC Directory has adjusted to be compliant with FERPA -  - I think - by suppressing information for some students at the students' request.

### Expected behavior
Email addresses, and any other protected information, for student contributors either do not display, or only display consistently with the permissions given by the student to the UC directory.

### Actual behavior
Email addresses display on the People page  and on the individual Profile page for a student contributor.

**Comment by crowesn** [comment]
@newmanld is this satisfied by #1897 ?

**Comment by newmanld** [comment]
@crowesn - No, not fully satisfied because a student's email address is still visible on their individual profile page.  My assumption is that if the student has requested that this information be suppressed in the UC directory, per FERPA, we should also suppress their email address (and other info?) on the profile page.  Can we find out from Shibboleth/UC directory if a student has set that privacy rule?

If suppressing info is problematic, when users with a student status submit works to Scholar@UC should we ask them to 'opt in' to display of some info their profile page - if not, say we are unable to accept the works?

Caveats - my understanding of FERPA is superficial at best.  No one at UC has told us we are not compliant, but read more at https://www2.ed.gov/policy/gen/guid/fpco/ferpa/index.html.

**Comment by newmanld** [comment]
And of course we need to distinguish between a student submitting as a proxy versus submitting on behalf of themselves.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/684
