### ISSUE TITLE
Use Research Directory /EProfessional API to pre-populate Profile Pages

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#19]
(See also Issue #18)
An API is available for UC's system known as Research Directory and EProfessional.  Some Colleges and Departments at UC use this to build faculty profile pages on their websites.  
Here is an example that I think might be built in this way:
http://pharmacy.uc.edu/faculty_profile.cfm?Action=PublicDoc&ePID=ODU5MA%3D%3D&code=webpage

Although this approach will be refined/informed by future feedback from our Early Adopters:
a) In a similar fashion, we should be able to populate user profile pages with information from EProfessional.  
b) Our users should be able to override this information on a field-by-field basis.

**Comment by jamesvanmil** [comment]
Depends on #1859

**Comment by scherztc** [comment]
This is the API URL construction tool:
 
                      http://webcentral.uc.edu/eprofapi/
 
Here are the environments (using the Get Me Someone’s Data API)
 
                      Production http://webcentral.uc.edu/eprof/cfc/fetcheprofdata.cfc?method=getWebPageData&userid=mccuisma
                      Scan/User http://scan.webcentral.uc.edu/eprof/cfc/fetcheprofdata.cfc?method=getWebPageData&userid=mccuisma
                      Development: http://systest.ahctest.uc.edu/eprof/cfc/fetcheprofdata.cfc?method=getWebPageData&userid=mccuisma

**Comment by scherztc** [comment]
https://webapps2.uc.edu/Researchapi/API/Getwebpagedata?userid=mccuisma

**Comment by scherztc** [comment]
Most do it from curly.libraries.uc.edu

**Comment by scherztc** [comment]
API Documentation : https://systest.ahctest.uc.edu/eprof/cfc/fetcheprofdatadoc.cfc?method=getdocumentation

**Comment by scherztc** [comment]
See example of API return on a 6+2 query:

https://git.uc.edu/UCLIBS/api-documentation/blob/master/research_directory/get_wb_page_data-sample-formatted.xml

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/707
