### ISSUE TITLE
Resolve display and faceting of all date fields

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#1906]
### Descriptive summary

Date Created  (not date uploaded) was a facet in Scholar 2.x.  It has disappeared from Scholar 3.x and this may have been unintentional or not fully vetted.  Review with P.O.s whether Date Created is a useful facet that should be restored.

Date Created is an optional field, and to sort as a facet correctly should be in the YYYY-MM-DD format (which is in the 'hint' for the field on the edit workform) and if it is a B.C.E. date should be preceded by a minus sign.  

Date  Uploaded and Date Modified are showing in the Catalog Browse but not on the work show page.  In the context of Hyrax 2.1, review with P.O.s where these system provided fields should display - on the Catalog Browse, and/or the Work Show page.

Generate specific issues after P.O. review.

**Comment by hortongn** [comment]
Moved remaining part of this issue to https://github.com/uclibs/ucrate/issues/683
