### ISSUE TITLE
Batch load - adjust to maintain order of files

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#1928]
### Descriptive summary

The order of files belonging to works matters for works we will export from the DRC.  It would be highly desirable if the batch load can maintain an order indicated by either:
   a) the default filename (ascending) sort order in a directory of files
and/or 
   b) the order of files as listed in the csv file.

It appears (more testing not a bad idea) that the folder upload now possible when uploading individual works in the GUI, does maintain filename order - at least in one case with 19 files, and using folder upload, this order was maintained. 

### Expected behavior
File order on individual works loaded via batch is predictable and can be controlled.

### Actual behavior
File order may be arbitrary.

**Comment by jamesvanmil** [comment]
I think this is working - need to test on QA. Blocked, pending security scanning to complete.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/729
