### ISSUE TITLE
File title from the batch csv isn't being applied

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc_legacy#1934]
### Descriptive summary

File title from the batch csv isn't being applied

### Expected behavior

File title should be added to files via batch upload

### Steps to reproduce the behavior

1. Upload a batch with file titles
2. Check to see if the files have a title other than the file title

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/607#issuecomment-468740137
