### ISSUE TITLE
Manage non-shibboleth accounts

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#1948]
### Descriptive summary
Non-Shibboleth accounts should be checked for:
 a) whether they are still needed
 b) whether we assigned a college and department (if a UC email address)

The first thing should be iterated periodically.

### Expected behavior
A non-shibboleth account with a UC email address should have a college and department assigned, so that content owned by that account will not be lost when faceting by College and Department.

An non-shibboleth account with a non-UC email address, established for someone acting as a proxy for a UC faculty member, should be removed when the project is done and the proxy relationship is no longer vital.  

I'll submit examples of Actual Behavior, which contain email addresses, to Slack.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/681
