### ISSUE TITLE
Custom Thumbnail for Work - explore - Submission_Use_Cases Submission 25

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#270]

**Comment by jamesvanmil** [comment]
Goal is to allow users to override the representative image for a file, which would allow them to select that thunbnail for the work.

**Comment by jamesvanmil** [comment]
Additionally, allow users to remove the custom representative image, which would kick off the worker to regenerate the old thumbnail.

**Comment by scherztc** [comment]
From the use_case repo:

As a: repository submitter

I want: to assign a thumbnail image for my work when I upload files (especially for video)

So that: I can choose the thumbnail image that displays to users when they search

Done looks like: a button on the input form that allows me to choose my thumbnail image

**Comment by jamesvanmil** [comment]
(Through our discussions) we've identified this as a complex use case. I think we should take time time to  break this out into a series of incremental improvements (esp. for works vs. files), to assess and prioritize in the context of the other needs.

**Comment by scherztc** [comment]
Here are the details of the Use Case:  https://github.com/uclibs/scholar_use_cases/blob/master/submission/submission_use_cases.md#submission-25---input-form--early-adopter

Technical Notes:
The work uses a representation of one of the attached files.  It gets this representation from the files thumbnail datastream in Fedora.  Files also use this datastream when representing a thumbnail.  Hydra uses FITS to create a smaller version of the file and save it in the same folder location.  A Collection in curate uses something called an avatar to show its representation.  This representation comes directly from the thumbnail datastream in the work.  We could use this avatar concept for this use case.

**Comment by newmanld** [comment]
I asked Eira Tansey for clarification as to the use case.  She agreed that addressing the use case was not 'Scholar 1.0' and provided the answers below.  

1)
Q - Does it solve the use case that users can already upload an image that will generate a thumbnail, just for the purpose of having a custom thumbnail?
A - No.  Having a file that is only intended to function as a thumbnail appearing on the works page under the “main” file(s) will likely be confusing to the majority of our users.

2)
Q - Does the use case imply that we should give the submitter more choice by extending Scholar@UC to auto-generate thumbnails for more work types, and/or add the ability to upload their own image to be a thumbnail?  
A - The last part – “add the ability to upload their own image to be a thumbnail” 

3)
Q  - Does the use case imply the submitter wants to be able to (optionally) upload a custom thumbnail image for the work that is different from the thumbnails associated with any of the attached files? 
A - This would be useful to have, again not a must-have for 1.0 functionality  

4)
Q - Does the use case imply that the submitter also wants to be able to (optionally) upload a custom thumbnail to override an auto-generated thumbnail for any attached file?
A  - This would be useful to have, again not a must-have for 1.0 functionality  

5)
Q - Is the custom thumbnail for the work (3 above) or for the attached file (4 above) more important to the use case or equally important?
A -  Custom thumbnail for the work is slightly more important than a custom thumbnail for a file. 

6)
Q - Is it important to be able to assign a custom thumbnail when first submitting a work or a file, or would the ability to do this when editing works or files suffice? 
A - Both. I doubt that many people will go back and edit things once they’ve submitted

7)
Q – Is it assumed that the capabilities given to submitters above are also given to Delegates and to Editors?
A - Yes
