### ISSUE TITLE
Progress Indicator needed when delays are possible - Scholar_Use_Cases - Submission 36

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#278]
Relating to file upload and Work Creation

**Comment by scherztc** [comment]
Two points of delays...

1.  File Upload
2.  Work submission

**Comment by scherztc** [comment]
@jamesvanmil noted that turbolinks needs to be addressed.

**Comment by crowesn** [comment]
Researching possibility of adding progress indicator directly without jquery-plugin.

**Comment by hortongn** [comment]
Depends on #657
