### ISSUE TITLE
Investigate word stemming and more sophisticated keyword search - Search_Retrieval_Use_Cases - Submission 14

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#290]
neighbor\* pulls in neighborhoods but 'neighbor' does not -- no automatic word stemming

integrate does not retrieve integrated

singular does pull up plural
behavior pulls up behaviors

Is this a SOLR configuration issue -- can we choose different Stemmers?

**Comment by scherztc** [comment]
This may be an help / tip question v. functionality question.

* and ? already work.  Research more.
