### ISSUE TITLE
Long profile section description doesn't wrap

### ISSUE THREAD

**Issue by 13miciunasl** [uclibs/scholar_uc_legacy#381]
Previously the description would wrap, extending the page vertically. Now the text does not wrap, extends the page horizontally, and displays over the users profile picture.

**Comment by hortongn** [comment]
I verified that this bug already exists on production (v0.13.0).  So this must have been introduced in a previous version.  At some point we can pull down previous tagged versions of our app and see when this first appeared.

**Comment by hortongn** [comment]
No longer an issue
