### ISSUE TITLE
Assign file titles on work submission

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#410]
As a content submitter, I want to assign file titles to each attached file when I first submit a new work, so that I do not have to return to the work and edit the work to assign file titles.

**Comment by newmanld** [comment]
May require new approach to multiple file upload when submitting a new work.

**Comment by newmanld** [comment]
See https://github.com/uclibs/scholar_use_cases/blob/master/submission/submission_use_cases.md#submission-42---submitting-multiple-files---early-adopter

**Comment by hortongn** [comment]
The uploadeder now allows users to specify a file title during upload
