### ISSUE TITLE
Replace an existing file with a new file from the cloud

### ISSUE THREAD

**Issue by newmanld** [uclibs/scholar_uc_legacy#412]
As a content editor, when I edit an existing file, I want to be able to replace it with a new file from the cloud, or replace it with one from my local workstation.

**Comment by newmanld** [comment]
Currently the user is only given the option, when editing a file, to replace it with one from their workstation.

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/703
