### ISSUE TITLE
Improve readability on additional pages

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc_legacy#431]
The text blocks in the welcome/help pages are too wide. Should be ~80 characters for web readability.

**Comment by jamesvanmil** [comment]
These layouts are used elsewhere: https://github.com/projecthydra-labs/curate/tree/68d7db006887eb52e3d46f38ac8814176ac8d620/app/views/layouts/curate_nd

Would be good to craft one of these for our text heavy pages, for easy reusability. They're invoked from the controller, e.g.: https://github.com/projecthydra-labs/curate/tree/68d7db006887eb52e3d46f38ac8814176ac8d620/app/views/layouts/curate_nd

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/672
