### ISSUE TITLE
Browse_Everything problems with .asc and .opd files

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#513]
User Feedback:  Hey, whenever I upload a .asc and .opd file from my box account, it gets automatically converted to .txt or .bin files. How do I overcome this issue?

**Comment by scherztc** [comment]
I am unsure whether or not this is till a problem and I am not sure if it is fixed in Hyrax 2.

**Comment by hortongn** [comment]
This is no longer a problem.
