### ISSUE TITLE
Video Work Type:  Resolve extent technical metadata for video files.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#592]

**Comment by scherztc** [comment]
With FITS 0.10.0 we are able to get duration into our characterization datastream:  http://larry.libraries.uc.edu:4001/fedora/objects/sufia:3484zh32z/datastreams/characterization/content

**Comment by scherztc** [comment]
There are also some new datastreams that come with the video work type:

webm	view content   video/webm
mp4	        view content   video/mp4

**Comment by scherztc** [comment]
Instructions for upgrading FITS to 0.10.0: https://github.com/projecthydra-labs/hydradam/wiki/Installation:-fits

**Comment by jamesvanmil** [comment]
@jamesvanmil will review this locally - use is pending FITS upgrade

**Comment by hortongn** [comment]
We are on a newer version of FITS now and a video's duration is now properly exposed on the file set page.

See example at https://scholar.uc.edu/concern/parent/j098zc116/file_sets/jh343t237?locale=en
