### ISSUE TITLE
Placeholder for Private Files showing up on Work Show pages

### ISSUE THREAD

**Issue by ntallman** [uclibs/scholar_uc_legacy#683]
An example can be seen here. [https://scholar.uc.edu/works/generic_works/05741r95w](https://scholar.uc.edu/works/generic_works/05741r95w)

Is this intentional or a bug? Clicking on File (filename field) take you to an unauthorized message.

**Comment by ntallman** [comment]
For embargoed files, a thumbnail image shows, but other metadata is not exposed (just says File). The file will not open.

**Comment by ntallman** [comment]
As a: research user
I want to: add files that are totally invisible to the public
So that: only I will see them or even know that they are there

**Comment by hortongn** [comment]
No longer an issue now that we have turned off the ability of users to see that private files are attached to works.
