### ISSUE TITLE
Upgrade FITS to 0.10.0

### ISSUE THREAD

**Issue by hortongn** [uclibs/scholar_uc_legacy#687]
Upgrade FITS to 0.10.0 in all server environments.  This is required to complete issue #592 

IT@UC help is needed to perform this upgrade on production.

**Comment by scherztc** [comment]
https://github.com/projecthydra-labs/hydradam/wiki/Installation:-fits

**Comment by scherztc** [comment]
Using the FITS 0.10.0 zip files:  http://fits.googlecode.com/files/fits-0.10.0.zip

**Comment by hortongn** [comment]
We are now on a higher version of FITS than this.
