### ISSUE TITLE
As Repository Manager, when I add a private file to a private work then the original owner can not see the attached file.

### ISSUE THREAD

**Issue by scherztc** [uclibs/scholar_uc_legacy#699]
When I added the private video file to your work as Repository Manager, I think it was also flagged as private to you also.

**Comment by jamesvanmil** [comment]
Kyle just wrapped up some work that ensures that the owner of new attached files is also the owner of the work. We could probably leverage that for a quick fix on permissions of new work, regardless of depositor.

**Comment by hortongn** [comment]
This is no longer a bug in Scholar 4.0
