### ISSUE TITLE
Multiple contributors to a collection

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc_legacy#731]
Organizing Content Use Case [Submission 10](https://github.com/uclibs/scholar_use_cases/blob/master/organizing_content/organizing_content_use_cases.md#submission-10---multiple-contributors-to-a-collection--early-adopter)

**Comment by newmanld** [comment]
Delegates should be able to add to a Collection that the Delegator has established.  Similarly, a collection owner should be able to assign editors and groups, indicating who can add works to a collection. This capability should be kept separate from any work to extend access and edit rights to all members of a collection - this issue should just be about building membership of collections themselves, and editing collection descriptions.

See this thread from a recent Hydra Tech Call: https://wiki.duraspace.org/display/hydra/Hydra+Tech+Call+2016-04-13

**Comment by hortongn** [comment]
These features now exist in Scholar 4.0 (from Hyrax 2.x)
