### ISSUE TITLE
Solr documents in production for deleted works

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc_legacy#769]
When trying to update the subjects on the textbook collection, we ran into a solr document result for a work that is not in Fedora. We suspect that errors related to collection size caused this object to only partially delete.

A Solr:reindex probably doesn't do anything with objects that Fedora doesn't know about, so if this was removed from Fedora without being removed from Solr, the document needs to be directly deleted from Solr. The quickest approach would be to wipe Solr and do a reindex - alternatively, we could target just the problematic documents.

**Comment by scherztc** [comment]
@jamesvanmil Can we close this with the update of the solr:reindex in Scholar 3?

**Comment by scherztc** [comment]
Confirm behavior.

**Comment by hortongn** [comment]
This is no longer an issue.
