### ISSUE TITLE
Expose file embargo dates on the work show page

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc_legacy#771]
The work is public, and the file is not. It would be good to display when the file is scheduled to come out of embargo (hopefully without cluttering it up much more)

![screen shot 2016-06-03 at 11 56 47 am](https://cloud.githubusercontent.com/assets/2651187/15784831/45805c68-2982-11e6-876b-276d99e0ca64.png)

**Comment by hortongn** [comment]
This is no longer a concern since files that a user does not have permission to see (private, embargoed, etc.) are no longer displayed on the work show page.  They are completely hidden now.
