### ISSUE TITLE
Research date format in Sufia

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc_legacy#831]
Dates should validate to standard ISO format. 

Errors in scholar 2.0, missing leading zeros, etc: 

![screen shot 2016-08-01 at 10 47 42 am](https://cloud.githubusercontent.com/assets/1069588/17297876/92390b82-57d5-11e6-9f55-17d3267b2def.png)

**Comment by jamesvanmil** [comment]
Adding to research task: accommodating date ranges, older dates

**Comment by jamesvanmil** [comment]
Consult with metadata SME on requirements

**Comment by crowesn** [comment]
Ideal requirements from SME conversation 1/19/2017
* Ideally validate BCE and CE ISO format dates and date ranges
* No circa dates

Possible acceptable outcomes (not mutually exclusive)
* possible help text with BCE and date range examples
* Make non-facetable field
* Facet year only

**Comment by crowesn** [comment]
Related #887

**Comment by scherztc** [comment]
Data Validation needs to occur on Degree_Date, Date_Created, Date_Digitized, ...

**Comment by hortongn** [comment]
Moved to https://github.com/uclibs/ucrate/issues/801
