### ISSUE TITLE
Add controlled field for authorship roles

### ISSUE THREAD

**Issue by crowesn** [uclibs/scholar_uc_legacy#872]
Added non-required select with controlled terms.

* author
* artist
* collector
* composer
* editor
* director
* musician
* photographer
* poet

**Comment by scherztc** [comment]
With Sufia 7.2 we are going to get the Questioning Authority gem that will provide authority control for fields.

**Comment by scherztc** [comment]
See:  https://github.com/projecthydra/sufia/wiki/Customizing-Metadata#customizing-the-work-type-to-include-a-controlled-vocabulary-property

**Comment by crowesn** [comment]
Checking with metadata SME about list of roles.

**Comment by crowesn** [comment]
For this issue we need to convert the default creator field to contain nested attributes: one for name and one for role. The role attribute must be controlled. There are instructions for adding a controlled vocab field in Sufia 7 [here](https://github.com/projecthydra/sufia/wiki/Customizing-Metadata#customizing-the-work-type-to-include-a-controlled-vocabulary-property). Documentation for overriding default fields for nesting in Sufia 7 are non-existant. There are some instructions for Sufia 6 but it's not clear that they map over cleanly. This is feeling like a 3.1 issue.
