### ISSUE TITLE
Issues with ownership transfer and proxies

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc_legacy#936]
I ran through the follow scenarios to test ownership transfer:
1. User 1, with no delegates - transfer to User 2 with no delegates
   - Works as expected
2. User 1, with no delegates - transfer to User 3 with User 4 as delegate
   - User 3 has access - as expected
   - User 4 does not have access - User 4 should have access as a delegate!!!
3. User 3, with User 4 as delegate - transfer to User 1 with no delegates
   - User 1 has access - as expected
   - User 4 does not have access - as expected
4. User 3, with work submitted by User 4 as delegate - transfer to User 1 with no delegates
   - User 1 has access - as expected
   - User 4 does not have access - as expected
   - User 3 still has access - should not have access!!!
5. User 3, with User 4 as delegate - transfer to User 2 with User 4 as delegate
   - User 2 has access - as expected
   - User 4 does not have access - User 4 should have access as a delegate!!!
6. User 3, with User 4 as delegate - transer to User 4 with no delegates
   - User 4 has access - as expected
7. User 3, with work submitted by User 4 as delegate - transfer to User 4 with no delegates
   - User 3 still has access - should not have access!!!
   - User 4 has access - as expected

In addition we also need the ownership transfer to verify that the new owner is a member of any groups on the work - removing them if they are not.

**Comment by scherztc** [comment]
I am not sure if all of this is solved in Hyrax 2.  Labelling it as Scholar 3.x until I can test all of it again.
